/// Flutter icons MapCovidApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MapCovidApp
///      fonts:
///       - asset: fonts/MapCovidApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VirusMapBRIcons {
  VirusMapBRIcons._();

  static const _kFontFam = 'VirusMapBRIcons';
  static const _kFontPkg = null;

  static const IconData alert_triangle = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_filled = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_outline = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData center_location = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dark_mode = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_filled = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_outline = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_mode = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_mark_filled = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_mark = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_filled = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_outline = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_filled = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_outline = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData okay = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_filled = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outline = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_filled = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_outline = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_icon = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_circular = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desviralize = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData termos = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
